/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";

export namespace Components {
  interface BingoButton {
    /**
     * URL for the anchor to point to
     */
    href: any;
    /**
     * Button size
     */
    size?: "big" | "small" | "block";
    /**
     * Button variation
     */
    variation?: "primary" | "link" | "success" | "error";
  }
  interface MyComponent {
    /**
     * The first name
     */
    first: string;
    /**
     * The last name
     */
    last: string;
    /**
     * The middle name
     */
    middle: string;
  }
}

declare global {
  interface HTMLBingoButtonElement
    extends Components.BingoButton,
      HTMLStencilElement {}
  var HTMLBingoButtonElement: {
    prototype: HTMLBingoButtonElement;
    new (): HTMLBingoButtonElement;
  };

  interface HTMLMyComponentElement
    extends Components.MyComponent,
      HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };
  interface HTMLElementTagNameMap {
    "bingo-button": HTMLBingoButtonElement;
    "my-component": HTMLMyComponentElement;
  }
}

declare namespace LocalJSX {
  interface BingoButton {
    /**
     * URL for the anchor to point to
     */
    href?: any;
    /**
     * Button size
     */
    size?: "big" | "small" | "block";
    /**
     * Button variation
     */
    variation?: "primary" | "link" | "success" | "error";
  }
  interface MyComponent {
    /**
     * The first name
     */
    first?: string;
    /**
     * The last name
     */
    last?: string;
    /**
     * The middle name
     */
    middle?: string;
  }

  interface IntrinsicElements {
    "bingo-button": BingoButton;
    "my-component": MyComponent;
  }
}

export { LocalJSX as JSX };

declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      "bingo-button": LocalJSX.BingoButton &
        JSXBase.HTMLAttributes<HTMLBingoButtonElement>;
      "my-component": LocalJSX.MyComponent &
        JSXBase.HTMLAttributes<HTMLMyComponentElement>;
    }
  }
}
